# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'decision.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_decision(object):
    def setupUi(self, decision):
        decision.setObjectName("decision")
        decision.resize(300, 300)
        decision.setMinimumSize(QtCore.QSize(300, 300))
        decision.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(decision)
        self.centralwidget.setObjectName("centralwidget")
        self.switch_case = QtWidgets.QPushButton(self.centralwidget)
        self.switch_case.setGeometry(QtCore.QRect(30, 70, 100, 100))
        self.switch_case.setMinimumSize(QtCore.QSize(100, 100))
        self.switch_case.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.switch_case.setFont(font)
        self.switch_case.setObjectName("switch_case")
        self.open_case = QtWidgets.QPushButton(self.centralwidget)
        self.open_case.setGeometry(QtCore.QRect(170, 70, 100, 100))
        self.open_case.setMinimumSize(QtCore.QSize(100, 100))
        self.open_case.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.open_case.setFont(font)
        self.open_case.setObjectName("open_case")
        decision.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(decision)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 26))
        self.menubar.setObjectName("menubar")
        decision.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(decision)
        self.statusbar.setObjectName("statusbar")
        decision.setStatusBar(self.statusbar)

        self.retranslateUi(decision)
        QtCore.QMetaObject.connectSlotsByName(decision)

    def retranslateUi(self, decision):
        _translate = QtCore.QCoreApplication.translate
        decision.setWindowTitle(_translate("decision", "Keep or Switch"))
        self.switch_case.setText(_translate("decision", "Switch\n"
"Case"))
        self.open_case.setText(_translate("decision", "Open\n"
"Case"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    decision = QtWidgets.QMainWindow()
    ui = Ui_decision()
    ui.setupUi(decision)
    decision.show()
    sys.exit(app.exec_())
